### ISSUE TITLE
Offer an ECMA Module version

### ISSUE THREAD

**Issue by leonard84** [omichelsen/compare-versions#41]
I'm using `compare-versions` in an Angular app, and Angular complains about using a commonJS/AMD module.
Would it be possible to convert this to an ECMA Module, or offer a ECMA Module version?
The ECMA version could then be the source of a converted commonJS/AMD version if that format is still necessary.

See also
https://web.dev/commonjs-larger-bundles/
https://angular.io/guide/build#configuring-commonjs-dependencies

**Comment by omichelsen** [comment]
We are using a UMD pattern which is compatible with CJS and AMD and the browser. In principle the articles you've linked are correct and ECMA is the new best practice but since this library doesn't include any dependencies, there's nothing to be tree shaken (no optimization necessary). As this is a pure JS source and we don't have any transforms I don't plan to add a separate ECMA version since it would require to either add unwanted tooling or copy paste the entire source code.

**Comment by leonard84** [comment]
Fair enough
