### ISSUE TITLE
difference in the validate function between 4 and 5

### ISSUE THREAD

**Issue by vidarc** [omichelsen/compare-versions#62]
In version 4.1.4
```javascript
validate('^1.0.0')
```
returns true

however, in version 5.0.1, this now returns false.

**Comment by omichelsen** [comment]
There was a bug in v4 resulting in slightly different behavior between the ESM and CJS version of the code as reported in #51 #50 and #52. This is now fixed in v5 and what you are seeing is the intended behavior. The leading `^` makes it a range so it's not a valid version. Ranges can be used in the `satisfies()` function.

**Comment by vidarc** [comment]
Gotcha, makes sense. I was thinking of range and version as one and the same.
